#
# Generated by RepositoryTask on 9/26/12 9:22 AM
#
# name = emi_2_0_sl6_i386_base
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/emi/2.0/sl6/i386/base/
#

structure template repository/emi_2_0_sl6_i386_base;

"name" = "emi_2_0_sl6_i386_base";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/emi/2.0/sl6/i386/base/")
);

"contents" = nlist(
);
