#
# Generated by RepositoryTask on 3/20/13 6:28 PM
#
# name = nagios
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/nagios
#

structure template repository/nagios;

"name" = "nagios";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/nagios")
);

"contents" = nlist(
# pkg = activemq-info-provider-5.1.0-7-noarch
escape("activemq-info-provider-5.1.0-7-noarch"),nlist("name","activemq-info-provider","version","5.1.0-7","arch","noarch"),
# pkg = egee-NAGIOS-1.0.0-11-noarch
escape("egee-NAGIOS-1.0.0-11-noarch"),nlist("name","egee-NAGIOS","version","1.0.0-11","arch","noarch"),
# pkg = fping-2.4-1.b2.2.el4.rf-x86_64
escape("fping-2.4-1.b2.2.el4.rf-x86_64"),nlist("name","fping","version","2.4-1.b2.2.el4.rf","arch","x86_64"),
# pkg = fping-2.4-1.b2.2.el5.rf-x86_64
escape("fping-2.4-1.b2.2.el5.rf-x86_64"),nlist("name","fping","version","2.4-1.b2.2.el5.rf","arch","x86_64"),
# pkg = glite-yaim-nagios-1.0.7-1-noarch
escape("glite-yaim-nagios-1.0.7-1-noarch"),nlist("name","glite-yaim-nagios","version","1.0.7-1","arch","noarch"),
# pkg = grid-monitoring-config-gen-0.10.5-1-noarch
escape("grid-monitoring-config-gen-0.10.5-1-noarch"),nlist("name","grid-monitoring-config-gen","version","0.10.5-1","arch","noarch"),
# pkg = grid-monitoring-config-gen-0.9.10-1-noarch
escape("grid-monitoring-config-gen-0.9.10-1-noarch"),nlist("name","grid-monitoring-config-gen","version","0.9.10-1","arch","noarch"),
# pkg = grid-monitoring-config-gen-0.9.11-2-noarch
escape("grid-monitoring-config-gen-0.9.11-2-noarch"),nlist("name","grid-monitoring-config-gen","version","0.9.11-2","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-local-0.10.1-1-noarch
escape("grid-monitoring-fm-nagios-local-0.10.1-1-noarch"),nlist("name","grid-monitoring-fm-nagios-local","version","0.10.1-1","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-local-0.10.2-0-noarch
escape("grid-monitoring-fm-nagios-local-0.10.2-0-noarch"),nlist("name","grid-monitoring-fm-nagios-local","version","0.10.2-0","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-local-0.11.1-1-noarch
escape("grid-monitoring-fm-nagios-local-0.11.1-1-noarch"),nlist("name","grid-monitoring-fm-nagios-local","version","0.11.1-1","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-remote-0.10.0-1-noarch
escape("grid-monitoring-fm-nagios-remote-0.10.0-1-noarch"),nlist("name","grid-monitoring-fm-nagios-remote","version","0.10.0-1","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-remote-0.10.1-1-noarch
escape("grid-monitoring-fm-nagios-remote-0.10.1-1-noarch"),nlist("name","grid-monitoring-fm-nagios-remote","version","0.10.1-1","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-remote-0.9.9-2-noarch
escape("grid-monitoring-fm-nagios-remote-0.9.9-2-noarch"),nlist("name","grid-monitoring-fm-nagios-remote","version","0.9.9-2","arch","noarch"),
# pkg = grid-monitoring-fm-nagios-remote-0.9.9-3-noarch
escape("grid-monitoring-fm-nagios-remote-0.9.9-3-noarch"),nlist("name","grid-monitoring-fm-nagios-remote","version","0.9.9-3","arch","noarch"),
# pkg = grid-monitoring-probes-ch.cern-0.12.0-1-i386
escape("grid-monitoring-probes-ch.cern-0.12.0-1-i386"),nlist("name","grid-monitoring-probes-ch.cern","version","0.12.0-1","arch","i386"),
# pkg = grid-monitoring-probes-ch.cern-0.9.2-1-noarch
escape("grid-monitoring-probes-ch.cern-0.9.2-1-noarch"),nlist("name","grid-monitoring-probes-ch.cern","version","0.9.2-1","arch","noarch"),
# pkg = grid-monitoring-probes-hr.srce-0.10.1-1-noarch
escape("grid-monitoring-probes-hr.srce-0.10.1-1-noarch"),nlist("name","grid-monitoring-probes-hr.srce","version","0.10.1-1","arch","noarch"),
# pkg = grid-monitoring-probes-hr.srce-0.9.5-0-noarch
escape("grid-monitoring-probes-hr.srce-0.9.5-0-noarch"),nlist("name","grid-monitoring-probes-hr.srce","version","0.9.5-0","arch","noarch"),
# pkg = grid-monitoring-probes-hr.srce-0.9.7-0-noarch
escape("grid-monitoring-probes-hr.srce-0.9.7-0-noarch"),nlist("name","grid-monitoring-probes-hr.srce","version","0.9.7-0","arch","noarch"),
# pkg = libmcrypt-2.5.7-1.2.el4.rf-x86_64
escape("libmcrypt-2.5.7-1.2.el4.rf-x86_64"),nlist("name","libmcrypt","version","2.5.7-1.2.el4.rf","arch","x86_64"),
# pkg = msg-nagios-bridge-0.9.6-1-noarch
escape("msg-nagios-bridge-0.9.6-1-noarch"),nlist("name","msg-nagios-bridge","version","0.9.6-1","arch","noarch"),
# pkg = msg-publish-simple-0.9.3-1-noarch
escape("msg-publish-simple-0.9.3-1-noarch"),nlist("name","msg-publish-simple","version","0.9.3-1","arch","noarch"),
# pkg = msg-publish-simple-0.9.7-3-noarch
escape("msg-publish-simple-0.9.7-3-noarch"),nlist("name","msg-publish-simple","version","0.9.7-3","arch","noarch"),
# pkg = nagios-2.10-1.el4.rf-x86_64
escape("nagios-2.10-1.el4.rf-x86_64"),nlist("name","nagios","version","2.10-1.el4.rf","arch","x86_64"),
# pkg = nagios-2.11-1.el4.rf-x86_64
escape("nagios-2.11-1.el4.rf-x86_64"),nlist("name","nagios","version","2.11-1.el4.rf","arch","x86_64"),
# pkg = nagios-2.11-1.el5.rf-x86_64
escape("nagios-2.11-1.el5.rf-x86_64"),nlist("name","nagios","version","2.11-1.el5.rf","arch","x86_64"),
# pkg = nagios-2.9-1.el5.rf-x86_64
escape("nagios-2.9-1.el5.rf-x86_64"),nlist("name","nagios","version","2.9-1.el5.rf","arch","x86_64"),
# pkg = nagios-3.0b3-1.SL3-i386
escape("nagios-3.0b3-1.SL3-i386"),nlist("name","nagios","version","3.0b3-1.SL3","arch","i386"),
# pkg = nagios-3.0b3-1.SL4-i386
escape("nagios-3.0b3-1.SL4-i386"),nlist("name","nagios","version","3.0b3-1.SL4","arch","i386"),
# pkg = nagios-3.0b5-SL3-i386
escape("nagios-3.0b5-SL3-i386"),nlist("name","nagios","version","3.0b5-SL3","arch","i386"),
# pkg = nagios-3.0b5-SL4-i386
escape("nagios-3.0b5-SL4-i386"),nlist("name","nagios","version","3.0b5-SL4","arch","i386"),
# pkg = nagios-3.0b6-SL3-i386
escape("nagios-3.0b6-SL3-i386"),nlist("name","nagios","version","3.0b6-SL3","arch","i386"),
# pkg = nagios-3.0b6-SL4-i386
escape("nagios-3.0b6-SL4-i386"),nlist("name","nagios","version","3.0b6-SL4","arch","i386"),
# pkg = nagios-3.0b7-SL3-i386
escape("nagios-3.0b7-SL3-i386"),nlist("name","nagios","version","3.0b7-SL3","arch","i386"),
# pkg = nagios-3.0b7-SL4-i386
escape("nagios-3.0b7-SL4-i386"),nlist("name","nagios","version","3.0b7-SL4","arch","i386"),
# pkg = nagios-debuginfo-3.0b3-1.SL3-i386
escape("nagios-debuginfo-3.0b3-1.SL3-i386"),nlist("name","nagios-debuginfo","version","3.0b3-1.SL3","arch","i386"),
# pkg = nagios-debuginfo-3.0b3-1.SL4-i386
escape("nagios-debuginfo-3.0b3-1.SL4-i386"),nlist("name","nagios-debuginfo","version","3.0b3-1.SL4","arch","i386"),
# pkg = nagios-debuginfo-3.0b5-SL4-i386
escape("nagios-debuginfo-3.0b5-SL4-i386"),nlist("name","nagios-debuginfo","version","3.0b5-SL4","arch","i386"),
# pkg = nagios-debuginfo-3.0b6-SL3-i386
escape("nagios-debuginfo-3.0b6-SL3-i386"),nlist("name","nagios-debuginfo","version","3.0b6-SL3","arch","i386"),
# pkg = nagios-debuginfo-3.0b6-SL4-i386
escape("nagios-debuginfo-3.0b6-SL4-i386"),nlist("name","nagios-debuginfo","version","3.0b6-SL4","arch","i386"),
# pkg = nagios-debuginfo-3.0b7-SL3-i386
escape("nagios-debuginfo-3.0b7-SL3-i386"),nlist("name","nagios-debuginfo","version","3.0b7-SL3","arch","i386"),
# pkg = nagios-debuginfo-3.0b7-SL4-i386
escape("nagios-debuginfo-3.0b7-SL4-i386"),nlist("name","nagios-debuginfo","version","3.0b7-SL4","arch","i386"),
# pkg = nagios-devel-3.0b3-1.SL3-i386
escape("nagios-devel-3.0b3-1.SL3-i386"),nlist("name","nagios-devel","version","3.0b3-1.SL3","arch","i386"),
# pkg = nagios-devel-3.0b3-1.SL4-i386
escape("nagios-devel-3.0b3-1.SL4-i386"),nlist("name","nagios-devel","version","3.0b3-1.SL4","arch","i386"),
# pkg = nagios-devel-3.0b5-SL4-i386
escape("nagios-devel-3.0b5-SL4-i386"),nlist("name","nagios-devel","version","3.0b5-SL4","arch","i386"),
# pkg = nagios-devel-3.0b6-SL3-i386
escape("nagios-devel-3.0b6-SL3-i386"),nlist("name","nagios-devel","version","3.0b6-SL3","arch","i386"),
# pkg = nagios-devel-3.0b6-SL4-i386
escape("nagios-devel-3.0b6-SL4-i386"),nlist("name","nagios-devel","version","3.0b6-SL4","arch","i386"),
# pkg = nagios-devel-3.0b7-SL3-i386
escape("nagios-devel-3.0b7-SL3-i386"),nlist("name","nagios-devel","version","3.0b7-SL3","arch","i386"),
# pkg = nagios-devel-3.0b7-SL4-i386
escape("nagios-devel-3.0b7-SL4-i386"),nlist("name","nagios-devel","version","3.0b7-SL4","arch","i386"),
# pkg = nagios-gocdb-downtime-0.13-2.el4-noarch
escape("nagios-gocdb-downtime-0.13-2.el4-noarch"),nlist("name","nagios-gocdb-downtime","version","0.13-2.el4","arch","noarch"),
# pkg = nagios-grid-plugins-0.1-1-i386
escape("nagios-grid-plugins-0.1-1-i386"),nlist("name","nagios-grid-plugins","version","0.1-1","arch","i386"),
# pkg = nagios-grid-plugins-0.10-1-noarch
escape("nagios-grid-plugins-0.10-1-noarch"),nlist("name","nagios-grid-plugins","version","0.10-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.11-1-noarch
escape("nagios-grid-plugins-0.11-1-noarch"),nlist("name","nagios-grid-plugins","version","0.11-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.12-1-noarch
escape("nagios-grid-plugins-0.12-1-noarch"),nlist("name","nagios-grid-plugins","version","0.12-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.13-1-noarch
escape("nagios-grid-plugins-0.13-1-noarch"),nlist("name","nagios-grid-plugins","version","0.13-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.13-2-noarch
escape("nagios-grid-plugins-0.13-2-noarch"),nlist("name","nagios-grid-plugins","version","0.13-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.13-3-noarch
escape("nagios-grid-plugins-0.13-3-noarch"),nlist("name","nagios-grid-plugins","version","0.13-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.14-1-noarch
escape("nagios-grid-plugins-0.14-1-noarch"),nlist("name","nagios-grid-plugins","version","0.14-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.14-2-noarch
escape("nagios-grid-plugins-0.14-2-noarch"),nlist("name","nagios-grid-plugins","version","0.14-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.14-3-noarch
escape("nagios-grid-plugins-0.14-3-noarch"),nlist("name","nagios-grid-plugins","version","0.14-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.14-4-noarch
escape("nagios-grid-plugins-0.14-4-noarch"),nlist("name","nagios-grid-plugins","version","0.14-4","arch","noarch"),
# pkg = nagios-grid-plugins-0.15-1-noarch
escape("nagios-grid-plugins-0.15-1-noarch"),nlist("name","nagios-grid-plugins","version","0.15-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.15-2-noarch
escape("nagios-grid-plugins-0.15-2-noarch"),nlist("name","nagios-grid-plugins","version","0.15-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.16-1-noarch
escape("nagios-grid-plugins-0.16-1-noarch"),nlist("name","nagios-grid-plugins","version","0.16-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.17-1-noarch
escape("nagios-grid-plugins-0.17-1-noarch"),nlist("name","nagios-grid-plugins","version","0.17-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.18-1-noarch
escape("nagios-grid-plugins-0.18-1-noarch"),nlist("name","nagios-grid-plugins","version","0.18-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.19-1-noarch
escape("nagios-grid-plugins-0.19-1-noarch"),nlist("name","nagios-grid-plugins","version","0.19-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.2-1-i386
escape("nagios-grid-plugins-0.2-1-i386"),nlist("name","nagios-grid-plugins","version","0.2-1","arch","i386"),
# pkg = nagios-grid-plugins-0.20-1-noarch
escape("nagios-grid-plugins-0.20-1-noarch"),nlist("name","nagios-grid-plugins","version","0.20-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.21-1-noarch
escape("nagios-grid-plugins-0.21-1-noarch"),nlist("name","nagios-grid-plugins","version","0.21-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.22-1-noarch
escape("nagios-grid-plugins-0.22-1-noarch"),nlist("name","nagios-grid-plugins","version","0.22-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.23-1-noarch
escape("nagios-grid-plugins-0.23-1-noarch"),nlist("name","nagios-grid-plugins","version","0.23-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.24-1-noarch
escape("nagios-grid-plugins-0.24-1-noarch"),nlist("name","nagios-grid-plugins","version","0.24-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.25-1-noarch
escape("nagios-grid-plugins-0.25-1-noarch"),nlist("name","nagios-grid-plugins","version","0.25-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.25-2-noarch
escape("nagios-grid-plugins-0.25-2-noarch"),nlist("name","nagios-grid-plugins","version","0.25-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.25-3-noarch
escape("nagios-grid-plugins-0.25-3-noarch"),nlist("name","nagios-grid-plugins","version","0.25-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.26-1-noarch
escape("nagios-grid-plugins-0.26-1-noarch"),nlist("name","nagios-grid-plugins","version","0.26-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.26-2-noarch
escape("nagios-grid-plugins-0.26-2-noarch"),nlist("name","nagios-grid-plugins","version","0.26-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.26-3-noarch
escape("nagios-grid-plugins-0.26-3-noarch"),nlist("name","nagios-grid-plugins","version","0.26-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.26-4-noarch
escape("nagios-grid-plugins-0.26-4-noarch"),nlist("name","nagios-grid-plugins","version","0.26-4","arch","noarch"),
# pkg = nagios-grid-plugins-0.27-1-noarch
escape("nagios-grid-plugins-0.27-1-noarch"),nlist("name","nagios-grid-plugins","version","0.27-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.27-2-noarch
escape("nagios-grid-plugins-0.27-2-noarch"),nlist("name","nagios-grid-plugins","version","0.27-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-1-noarch
escape("nagios-grid-plugins-0.28-1-noarch"),nlist("name","nagios-grid-plugins","version","0.28-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-10-noarch
escape("nagios-grid-plugins-0.28-10-noarch"),nlist("name","nagios-grid-plugins","version","0.28-10","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-11-noarch
escape("nagios-grid-plugins-0.28-11-noarch"),nlist("name","nagios-grid-plugins","version","0.28-11","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-12-noarch
escape("nagios-grid-plugins-0.28-12-noarch"),nlist("name","nagios-grid-plugins","version","0.28-12","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-13-noarch
escape("nagios-grid-plugins-0.28-13-noarch"),nlist("name","nagios-grid-plugins","version","0.28-13","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-14-noarch
escape("nagios-grid-plugins-0.28-14-noarch"),nlist("name","nagios-grid-plugins","version","0.28-14","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-2-noarch
escape("nagios-grid-plugins-0.28-2-noarch"),nlist("name","nagios-grid-plugins","version","0.28-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-3-noarch
escape("nagios-grid-plugins-0.28-3-noarch"),nlist("name","nagios-grid-plugins","version","0.28-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-4-noarch
escape("nagios-grid-plugins-0.28-4-noarch"),nlist("name","nagios-grid-plugins","version","0.28-4","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-5-noarch
escape("nagios-grid-plugins-0.28-5-noarch"),nlist("name","nagios-grid-plugins","version","0.28-5","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-6-noarch
escape("nagios-grid-plugins-0.28-6-noarch"),nlist("name","nagios-grid-plugins","version","0.28-6","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-7-noarch
escape("nagios-grid-plugins-0.28-7-noarch"),nlist("name","nagios-grid-plugins","version","0.28-7","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-8-noarch
escape("nagios-grid-plugins-0.28-8-noarch"),nlist("name","nagios-grid-plugins","version","0.28-8","arch","noarch"),
# pkg = nagios-grid-plugins-0.28-9-noarch
escape("nagios-grid-plugins-0.28-9-noarch"),nlist("name","nagios-grid-plugins","version","0.28-9","arch","noarch"),
# pkg = nagios-grid-plugins-0.29-1-noarch
escape("nagios-grid-plugins-0.29-1-noarch"),nlist("name","nagios-grid-plugins","version","0.29-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.3-1-i386
escape("nagios-grid-plugins-0.3-1-i386"),nlist("name","nagios-grid-plugins","version","0.3-1","arch","i386"),
# pkg = nagios-grid-plugins-0.30-1-noarch
escape("nagios-grid-plugins-0.30-1-noarch"),nlist("name","nagios-grid-plugins","version","0.30-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.30-2-noarch
escape("nagios-grid-plugins-0.30-2-noarch"),nlist("name","nagios-grid-plugins","version","0.30-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.30-3-noarch
escape("nagios-grid-plugins-0.30-3-noarch"),nlist("name","nagios-grid-plugins","version","0.30-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.30-4-noarch
escape("nagios-grid-plugins-0.30-4-noarch"),nlist("name","nagios-grid-plugins","version","0.30-4","arch","noarch"),
# pkg = nagios-grid-plugins-0.30-5-noarch
escape("nagios-grid-plugins-0.30-5-noarch"),nlist("name","nagios-grid-plugins","version","0.30-5","arch","noarch"),
# pkg = nagios-grid-plugins-0.30-6-noarch
escape("nagios-grid-plugins-0.30-6-noarch"),nlist("name","nagios-grid-plugins","version","0.30-6","arch","noarch"),
# pkg = nagios-grid-plugins-0.31-1-noarch
escape("nagios-grid-plugins-0.31-1-noarch"),nlist("name","nagios-grid-plugins","version","0.31-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.32-1-noarch
escape("nagios-grid-plugins-0.32-1-noarch"),nlist("name","nagios-grid-plugins","version","0.32-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.33-1-noarch
escape("nagios-grid-plugins-0.33-1-noarch"),nlist("name","nagios-grid-plugins","version","0.33-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.34-1-noarch
escape("nagios-grid-plugins-0.34-1-noarch"),nlist("name","nagios-grid-plugins","version","0.34-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.34-2-noarch
escape("nagios-grid-plugins-0.34-2-noarch"),nlist("name","nagios-grid-plugins","version","0.34-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.34-3-noarch
escape("nagios-grid-plugins-0.34-3-noarch"),nlist("name","nagios-grid-plugins","version","0.34-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-0-noarch
escape("nagios-grid-plugins-0.35-0-noarch"),nlist("name","nagios-grid-plugins","version","0.35-0","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-1-noarch
escape("nagios-grid-plugins-0.35-1-noarch"),nlist("name","nagios-grid-plugins","version","0.35-1","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-2-noarch
escape("nagios-grid-plugins-0.35-2-noarch"),nlist("name","nagios-grid-plugins","version","0.35-2","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-3-noarch
escape("nagios-grid-plugins-0.35-3-noarch"),nlist("name","nagios-grid-plugins","version","0.35-3","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-4-noarch
escape("nagios-grid-plugins-0.35-4-noarch"),nlist("name","nagios-grid-plugins","version","0.35-4","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-5-noarch
escape("nagios-grid-plugins-0.35-5-noarch"),nlist("name","nagios-grid-plugins","version","0.35-5","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-6-noarch
escape("nagios-grid-plugins-0.35-6-noarch"),nlist("name","nagios-grid-plugins","version","0.35-6","arch","noarch"),
# pkg = nagios-grid-plugins-0.35-7-noarch
escape("nagios-grid-plugins-0.35-7-noarch"),nlist("name","nagios-grid-plugins","version","0.35-7","arch","noarch"),
# pkg = nagios-grid-plugins-0.4-1-i386
escape("nagios-grid-plugins-0.4-1-i386"),nlist("name","nagios-grid-plugins","version","0.4-1","arch","i386"),
# pkg = nagios-grid-plugins-0.5-1-i386
escape("nagios-grid-plugins-0.5-1-i386"),nlist("name","nagios-grid-plugins","version","0.5-1","arch","i386"),
# pkg = nagios-grid-plugins-0.6-1-i386
escape("nagios-grid-plugins-0.6-1-i386"),nlist("name","nagios-grid-plugins","version","0.6-1","arch","i386"),
# pkg = nagios-grid-plugins-0.7-1-i386
escape("nagios-grid-plugins-0.7-1-i386"),nlist("name","nagios-grid-plugins","version","0.7-1","arch","i386"),
# pkg = nagios-grid-plugins-0.8-1-i386
escape("nagios-grid-plugins-0.8-1-i386"),nlist("name","nagios-grid-plugins","version","0.8-1","arch","i386"),
# pkg = nagios-grid-plugins-0.9-1-noarch
escape("nagios-grid-plugins-0.9-1-noarch"),nlist("name","nagios-grid-plugins","version","0.9-1","arch","noarch"),
# pkg = nagios-htpasswd-0.2-1-noarch
escape("nagios-htpasswd-0.2-1-noarch"),nlist("name","nagios-htpasswd","version","0.2-1","arch","noarch"),
# pkg = nagios-nrpe-2.5.2-1.el4.rf-x86_64
escape("nagios-nrpe-2.5.2-1.el4.rf-x86_64"),nlist("name","nagios-nrpe","version","2.5.2-1.el4.rf","arch","x86_64"),
# pkg = nagios-nrpe-2.5.2-1.el5.rf-x86_64
escape("nagios-nrpe-2.5.2-1.el5.rf-x86_64"),nlist("name","nagios-nrpe","version","2.5.2-1.el5.rf","arch","x86_64"),
# pkg = nagios-plugins-1.4.11-1.el4.rf-x86_64
escape("nagios-plugins-1.4.11-1.el4.rf-x86_64"),nlist("name","nagios-plugins","version","1.4.11-1.el4.rf","arch","x86_64"),
# pkg = nagios-plugins-1.4.11-1.el5.rf-x86_64
escape("nagios-plugins-1.4.11-1.el5.rf-x86_64"),nlist("name","nagios-plugins","version","1.4.11-1.el5.rf","arch","x86_64"),
# pkg = nagios-plugins-1.4.9-1-i386
escape("nagios-plugins-1.4.9-1-i386"),nlist("name","nagios-plugins","version","1.4.9-1","arch","i386"),
# pkg = nagios-plugins-1.4.9-1.el4.rf-x86_64
escape("nagios-plugins-1.4.9-1.el4.rf-x86_64"),nlist("name","nagios-plugins","version","1.4.9-1.el4.rf","arch","x86_64"),
# pkg = nagios-plugins-debuginfo-1.4.9-1-i386
escape("nagios-plugins-debuginfo-1.4.9-1-i386"),nlist("name","nagios-plugins-debuginfo","version","1.4.9-1","arch","i386"),
# pkg = nagios-plugins-lal-0-1-noarch
escape("nagios-plugins-lal-0-1-noarch"),nlist("name","nagios-plugins-lal","version","0-1","arch","noarch"),
# pkg = nagios-plugins-nrpe-2.5.2-1.el4.rf-x86_64
escape("nagios-plugins-nrpe-2.5.2-1.el4.rf-x86_64"),nlist("name","nagios-plugins-nrpe","version","2.5.2-1.el4.rf","arch","x86_64"),
# pkg = nagios-plugins-nrpe-2.5.2-1.el5.rf-x86_64
escape("nagios-plugins-nrpe-2.5.2-1.el5.rf-x86_64"),nlist("name","nagios-plugins-nrpe","version","2.5.2-1.el5.rf","arch","x86_64"),
# pkg = nagios-proxy-refresh-1.7-3-noarch
escape("nagios-proxy-refresh-1.7-3-noarch"),nlist("name","nagios-proxy-refresh","version","1.7-3","arch","noarch"),
# pkg = nagios-www-3.0b3-1.SL3-i386
escape("nagios-www-3.0b3-1.SL3-i386"),nlist("name","nagios-www","version","3.0b3-1.SL3","arch","i386"),
# pkg = nagios-www-3.0b3-1.SL4-i386
escape("nagios-www-3.0b3-1.SL4-i386"),nlist("name","nagios-www","version","3.0b3-1.SL4","arch","i386"),
# pkg = nagios-www-3.0b5-SL3-i386
escape("nagios-www-3.0b5-SL3-i386"),nlist("name","nagios-www","version","3.0b5-SL3","arch","i386"),
# pkg = nagios-www-3.0b5-SL4-i386
escape("nagios-www-3.0b5-SL4-i386"),nlist("name","nagios-www","version","3.0b5-SL4","arch","i386"),
# pkg = nagios-www-3.0b6-SL3-i386
escape("nagios-www-3.0b6-SL3-i386"),nlist("name","nagios-www","version","3.0b6-SL3","arch","i386"),
# pkg = nagios-www-3.0b6-SL4-i386
escape("nagios-www-3.0b6-SL4-i386"),nlist("name","nagios-www","version","3.0b6-SL4","arch","i386"),
# pkg = nagios-www-3.0b7-SL3-i386
escape("nagios-www-3.0b7-SL3-i386"),nlist("name","nagios-www","version","3.0b7-SL3","arch","i386"),
# pkg = nagios-www-3.0b7-SL4-i386
escape("nagios-www-3.0b7-SL4-i386"),nlist("name","nagios-www","version","3.0b7-SL4","arch","i386"),
# pkg = nrpe-2.10-1-i386
escape("nrpe-2.10-1-i386"),nlist("name","nrpe","version","2.10-1","arch","i386"),
# pkg = nrpe-2.8.1-1-i386
escape("nrpe-2.8.1-1-i386"),nlist("name","nrpe","version","2.8.1-1","arch","i386"),
# pkg = nrpe-debuginfo-2.10-1-i386
escape("nrpe-debuginfo-2.10-1-i386"),nlist("name","nrpe-debuginfo","version","2.10-1","arch","i386"),
# pkg = nrpe-debuginfo-2.8.1-1-i386
escape("nrpe-debuginfo-2.8.1-1-i386"),nlist("name","nrpe-debuginfo","version","2.8.1-1","arch","i386"),
# pkg = nrpe-plugin-2.10-1-i386
escape("nrpe-plugin-2.10-1-i386"),nlist("name","nrpe-plugin","version","2.10-1","arch","i386"),
# pkg = nrpe-plugin-2.8.1-1-i386
escape("nrpe-plugin-2.8.1-1-i386"),nlist("name","nrpe-plugin","version","2.8.1-1","arch","i386"),
# pkg = perl-Class-Accessor-0.31-1.el4.rf-noarch
escape("perl-Class-Accessor-0.31-1.el4.rf-noarch"),nlist("name","perl-Class-Accessor","version","0.31-1.el4.rf","arch","noarch"),
# pkg = perl-Config-General-2.27-1.2.el4.rf-noarch
escape("perl-Config-General-2.27-1.2.el4.rf-noarch"),nlist("name","perl-Config-General","version","2.27-1.2.el4.rf","arch","noarch"),
# pkg = perl-Config-General-2.40-1.el4.rf-noarch
escape("perl-Config-General-2.40-1.el4.rf-noarch"),nlist("name","perl-Config-General","version","2.40-1.el4.rf","arch","noarch"),
# pkg = perl-Config-Tiny-2.12-1.el4.rf-noarch
escape("perl-Config-Tiny-2.12-1.el4.rf-noarch"),nlist("name","perl-Config-Tiny","version","2.12-1.el4.rf","arch","noarch"),
# pkg = perl-Crypt-OpenSSL-X509-0.7-1.el4.rf-x86_64
escape("perl-Crypt-OpenSSL-X509-0.7-1.el4.rf-x86_64"),nlist("name","perl-Crypt-OpenSSL-X509","version","0.7-1.el4.rf","arch","x86_64"),
# pkg = perl-Curses-1.24-1.el4.rf-i386
escape("perl-Curses-1.24-1.el4.rf-i386"),nlist("name","perl-Curses","version","1.24-1.el4.rf","arch","i386"),
# pkg = perl-Devel-Symdump-2.08-1.el4.rf-noarch
escape("perl-Devel-Symdump-2.08-1.el4.rf-noarch"),nlist("name","perl-Devel-Symdump","version","2.08-1.el4.rf","arch","noarch"),
# pkg = perl-Digest-CRC-0.14-2.el4-noarch
escape("perl-Digest-CRC-0.14-2.el4-noarch"),nlist("name","perl-Digest-CRC","version","0.14-2.el4","arch","noarch"),
# pkg = perl-File-Remove-1.42-1.el4.rf-noarch
escape("perl-File-Remove-1.42-1.el4.rf-noarch"),nlist("name","perl-File-Remove","version","1.42-1.el4.rf","arch","noarch"),
# pkg = perl-GridMon-1.0.1-1-noarch
escape("perl-GridMon-1.0.1-1-noarch"),nlist("name","perl-GridMon","version","1.0.1-1","arch","noarch"),
# pkg = perl-GridMon-1.0.2-1-noarch
escape("perl-GridMon-1.0.2-1-noarch"),nlist("name","perl-GridMon","version","1.0.2-1","arch","noarch"),
# pkg = perl-GridMon-1.0.22-2.el4-noarch
escape("perl-GridMon-1.0.22-2.el4-noarch"),nlist("name","perl-GridMon","version","1.0.22-2.el4","arch","noarch"),
# pkg = perl-IPC-DirQueue-1.0-1.el4.rf-noarch
escape("perl-IPC-DirQueue-1.0-1.el4.rf-noarch"),nlist("name","perl-IPC-DirQueue","version","1.0-1.el4.rf","arch","noarch"),
# pkg = perl-JSON-1.07-1.el4.rf-noarch
escape("perl-JSON-1.07-1.el4.rf-noarch"),nlist("name","perl-JSON","version","1.07-1.el4.rf","arch","noarch"),
# pkg = perl-Math-Calc-Units-1.07-1.el4.rf-noarch
escape("perl-Math-Calc-Units-1.07-1.el4.rf-noarch"),nlist("name","perl-Math-Calc-Units","version","1.07-1.el4.rf","arch","noarch"),
# pkg = perl-Mcrypt-2.5.7.0-2.el4-x86_64
escape("perl-Mcrypt-2.5.7.0-2.el4-x86_64"),nlist("name","perl-Mcrypt","version","2.5.7.0-2.el4","arch","x86_64"),
# pkg = perl-Module-Install-0.91-1.el4.rf-noarch
escape("perl-Module-Install-0.91-1.el4.rf-noarch"),nlist("name","perl-Module-Install","version","0.91-1.el4.rf","arch","noarch"),
# pkg = perl-Nagios-NSCA-0.1-2.el4-noarch
escape("perl-Nagios-NSCA-0.1-2.el4-noarch"),nlist("name","perl-Nagios-NSCA","version","0.1-2.el4","arch","noarch"),
# pkg = perl-Nagios-Plugin-0.24-1.el4.rf-noarch
escape("perl-Nagios-Plugin-0.24-1.el4.rf-noarch"),nlist("name","perl-Nagios-Plugin","version","0.24-1.el4.rf","arch","noarch"),
# pkg = perl-Net-Stomp-0.34-1-noarch
escape("perl-Net-Stomp-0.34-1-noarch"),nlist("name","perl-Net-Stomp","version","0.34-1","arch","noarch"),
# pkg = perl-POE-1.0002-1.el4.rf-noarch
escape("perl-POE-1.0002-1.el4.rf-noarch"),nlist("name","perl-POE","version","1.0002-1.el4.rf","arch","noarch"),
# pkg = perl-Params-Validate-0.91-1.el4.rf-x86_64
escape("perl-Params-Validate-0.91-1.el4.rf-x86_64"),nlist("name","perl-Params-Validate","version","0.91-1.el4.rf","arch","x86_64"),
# pkg = perl-Pod-Coverage-0.20-1.el4.rf-noarch
escape("perl-Pod-Coverage-0.20-1.el4.rf-noarch"),nlist("name","perl-Pod-Coverage","version","0.20-1.el4.rf","arch","noarch"),
# pkg = perl-Spiffy-0.30-1.el4.rf-noarch
escape("perl-Spiffy-0.30-1.el4.rf-noarch"),nlist("name","perl-Spiffy","version","0.30-1.el4.rf","arch","noarch"),
# pkg = perl-Sub-Uplevel-0.2002-1.el4.rf-noarch
escape("perl-Sub-Uplevel-0.2002-1.el4.rf-noarch"),nlist("name","perl-Sub-Uplevel","version","0.2002-1.el4.rf","arch","noarch"),
# pkg = perl-Test-Base-0.59-1.el4.rf-noarch
escape("perl-Test-Base-0.59-1.el4.rf-noarch"),nlist("name","perl-Test-Base","version","0.59-1.el4.rf","arch","noarch"),
# pkg = perl-Test-Exception-0.27-1.el4.rf-noarch
escape("perl-Test-Exception-0.27-1.el4.rf-noarch"),nlist("name","perl-Test-Exception","version","0.27-1.el4.rf","arch","noarch"),
# pkg = perl-Test-Pod-1.40-1.el4.rf-noarch
escape("perl-Test-Pod-1.40-1.el4.rf-noarch"),nlist("name","perl-Test-Pod","version","1.40-1.el4.rf","arch","noarch"),
# pkg = perl-Test-Pod-Coverage-1.08-1.el4.rf-noarch
escape("perl-Test-Pod-Coverage-1.08-1.el4.rf-noarch"),nlist("name","perl-Test-Pod-Coverage","version","1.08-1.el4.rf","arch","noarch"),
# pkg = perl-Time-HiRes-1.9715-1.el4.rf-x86_64
escape("perl-Time-HiRes-1.9715-1.el4.rf-x86_64"),nlist("name","perl-Time-HiRes","version","1.9715-1.el4.rf","arch","x86_64"),
# pkg = perl-Tk-804.028-2.el4.rf-i386
escape("perl-Tk-804.028-2.el4.rf-i386"),nlist("name","perl-Tk","version","804.028-2.el4.rf","arch","i386"),
# pkg = perl-XML-Writer-0.520-1.2.el4.rf-noarch
escape("perl-XML-Writer-0.520-1.2.el4.rf-noarch"),nlist("name","perl-XML-Writer","version","0.520-1.2.el4.rf","arch","noarch"),
# pkg = perl-XML-Writer-0.604-1.el4.rf-noarch
escape("perl-XML-Writer-0.604-1.el4.rf-noarch"),nlist("name","perl-XML-Writer","version","0.604-1.el4.rf","arch","noarch"),
# pkg = perl-YAML-0.70-1.el4.rf-noarch
escape("perl-YAML-0.70-1.el4.rf-noarch"),nlist("name","perl-YAML","version","0.70-1.el4.rf","arch","noarch"),
# pkg = perl-YAML-Tiny-1.40-1.el4.rf-noarch
escape("perl-YAML-Tiny-1.40-1.el4.rf-noarch"),nlist("name","perl-YAML-Tiny","version","1.40-1.el4.rf","arch","noarch"),
# pkg = voms2htpasswd-1.3-1-noarch
escape("voms2htpasswd-1.3-1-noarch"),nlist("name","voms2htpasswd","version","1.3-1","arch","noarch"),
);
