#
# Generated by RepositoryTask on 14/04/11 10:54
#
# name = pakiti
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/pakiti
#

structure template repository/pakiti;

"name" = "pakiti";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/pakiti")
);

"contents" = nlist(
# pkg = pakiti-client-2.1.4-1-noarch
escape("pakiti-client-2.1.4-1-noarch"),nlist("name","pakiti-client","version","2.1.4-1","arch","noarch"),
# pkg = pakiti-client-2.1.4-2-noarch
escape("pakiti-client-2.1.4-2-noarch"),nlist("name","pakiti-client","version","2.1.4-2","arch","noarch"),
# pkg = pakiti-client-2.1.4-3-noarch
escape("pakiti-client-2.1.4-3-noarch"),nlist("name","pakiti-client","version","2.1.4-3","arch","noarch"),
# pkg = pakiti-client-2.1.4-4-noarch
escape("pakiti-client-2.1.4-4-noarch"),nlist("name","pakiti-client","version","2.1.4-4","arch","noarch"),
# pkg = pakiti-client-manual-2.1.4-2-noarch
escape("pakiti-client-manual-2.1.4-2-noarch"),nlist("name","pakiti-client-manual","version","2.1.4-2","arch","noarch"),
# pkg = pakiti-client-manual-2.1.4-3-noarch
escape("pakiti-client-manual-2.1.4-3-noarch"),nlist("name","pakiti-client-manual","version","2.1.4-3","arch","noarch"),
# pkg = pakiti-client-manual-2.1.4-4-noarch
escape("pakiti-client-manual-2.1.4-4-noarch"),nlist("name","pakiti-client-manual","version","2.1.4-4","arch","noarch"),
# pkg = pakiti-server-2.1.4-1-noarch
escape("pakiti-server-2.1.4-1-noarch"),nlist("name","pakiti-server","version","2.1.4-1","arch","noarch"),
# pkg = pakiti-server-2.1.4-2-noarch
escape("pakiti-server-2.1.4-2-noarch"),nlist("name","pakiti-server","version","2.1.4-2","arch","noarch"),
# pkg = pakiti-server-2.1.4-3-noarch
escape("pakiti-server-2.1.4-3-noarch"),nlist("name","pakiti-server","version","2.1.4-3","arch","noarch"),
# pkg = pakiti-server-2.1.4-4-noarch
escape("pakiti-server-2.1.4-4-noarch"),nlist("name","pakiti-server","version","2.1.4-4","arch","noarch"),
);
