#
# Generated by RepositoryTask on 18/07/11 14:43
#
# name = sl460_x86_64_updates
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/os/sl460-x86_64/updates
#

structure template repository/sl460_x86_64_updates;

"name" = "sl460_x86_64_updates";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/os/sl460-x86_64/updates")
);

"contents" = nlist(
# pkg = HDLM-5.93.0.584-11-x86_64
escape("HDLM-5.93.0.584-11-x86_64"),nlist("name","HDLM","version","5.93.0.584-11","arch","x86_64"),
# pkg = HDLM-5.94.2.584-1-x86_64
escape("HDLM-5.94.2.584-1-x86_64"),nlist("name","HDLM","version","5.94.2.584-1","arch","x86_64"),
# pkg = HDLM-6.2.0.0.584-9-x86_64
escape("HDLM-6.2.0.0.584-9-x86_64"),nlist("name","HDLM","version","6.2.0.0.584-9","arch","x86_64"),
# pkg = ORBit-0.5.17-14-i386
escape("ORBit-0.5.17-14-i386"),nlist("name","ORBit","version","0.5.17-14","arch","i386"),
# pkg = cmake-2.4.6-2.el4-i386
escape("cmake-2.4.6-2.el4-i386"),nlist("name","cmake","version","2.4.6-2.el4","arch","i386"),
# pkg = cmake-2.4.6-2.el4-x86_64
escape("cmake-2.4.6-2.el4-x86_64"),nlist("name","cmake","version","2.4.6-2.el4","arch","x86_64"),
# pkg = createrepo-0.9.5-2-noarch
escape("createrepo-0.9.5-2-noarch"),nlist("name","createrepo","version","0.9.5-2","arch","noarch"),
# pkg = curl-compat-7.10.6-6-1.0.0-1-i386
escape("curl-compat-7.10.6-6-1.0.0-1-i386"),nlist("name","curl-compat-7.10.6-6","version","1.0.0-1","arch","i386"),
# pkg = dmapi-2.2.0-1.SL-x86_64
escape("dmapi-2.2.0-1.SL-x86_64"),nlist("name","dmapi","version","2.2.0-1.SL","arch","x86_64"),
# pkg = dmapi-2.2.8-1.sl4-x86_64
escape("dmapi-2.2.8-1.sl4-x86_64"),nlist("name","dmapi","version","2.2.8-1.sl4","arch","x86_64"),
# pkg = dmapi-debuginfo-2.2.8-1.sl4-x86_64
escape("dmapi-debuginfo-2.2.8-1.sl4-x86_64"),nlist("name","dmapi-debuginfo","version","2.2.8-1.sl4","arch","x86_64"),
# pkg = dmapi-devel-2.2.0-1.SL-x86_64
escape("dmapi-devel-2.2.0-1.SL-x86_64"),nlist("name","dmapi-devel","version","2.2.0-1.SL","arch","x86_64"),
# pkg = dmapi-devel-2.2.8-1.sl4-x86_64
escape("dmapi-devel-2.2.8-1.sl4-x86_64"),nlist("name","dmapi-devel","version","2.2.8-1.sl4","arch","x86_64"),
# pkg = iperf-2.0.2-1.2.el4.rf-x86_64
escape("iperf-2.0.2-1.2.el4.rf-x86_64"),nlist("name","iperf","version","2.0.2-1.2.el4.rf","arch","x86_64"),
# pkg = itcl-3.2-92.4-i386
escape("itcl-3.2-92.4-i386"),nlist("name","itcl","version","3.2-92.4","arch","i386"),
# pkg = java-1.5.0-sun-compat-1.5.0.14-1jpp-i586
escape("java-1.5.0-sun-compat-1.5.0.14-1jpp-i586"),nlist("name","java-1.5.0-sun-compat","version","1.5.0.14-1jpp","arch","i586"),
# pkg = jpackage-utils-1.7.4-2jppmj-noarch
escape("jpackage-utils-1.7.4-2jppmj-noarch"),nlist("name","jpackage-utils","version","1.7.4-2jppmj","arch","noarch"),
# pkg = kernel-2.6.26.5virtio3-1-x86_64
escape("kernel-2.6.26.5virtio3-1-x86_64"),nlist("name","kernel","version","2.6.26.5virtio3-1","arch","x86_64"),
# pkg = kernel-2.6.30.5virtio2-1-x86_64
escape("kernel-2.6.30.5virtio2-1-x86_64"),nlist("name","kernel","version","2.6.30.5virtio2-1","arch","x86_64"),
# pkg = kernel-2.6.30.5virtio3-1-x86_64
escape("kernel-2.6.30.5virtio3-1-x86_64"),nlist("name","kernel","version","2.6.30.5virtio3-1","arch","x86_64"),
# pkg = kernel-2.6.31.6virtio1-1-x86_64
escape("kernel-2.6.31.6virtio1-1-x86_64"),nlist("name","kernel","version","2.6.31.6virtio1-1","arch","x86_64"),
# pkg = kernel-2.6.35.13virtio1-1-x86_64
escape("kernel-2.6.35.13virtio1-1-x86_64"),nlist("name","kernel","version","2.6.35.13virtio1-1","arch","x86_64"),
# pkg = kernel-2.6.38.3virtio1-1-x86_64
escape("kernel-2.6.38.3virtio1-1-x86_64"),nlist("name","kernel","version","2.6.38.3virtio1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.12.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.12.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.12.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.2.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.2.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.2.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.2.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.2.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.2.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.2.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.2.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.2.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.2.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.2.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.2.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.6.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.6.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.6.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.0.9.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.0.9.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.0.9.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-55.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-55.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-55.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.1.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.1.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.1.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.15.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.15.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.15.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.15.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.15.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.15.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.15.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.15.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.15.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.15.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.15.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.15.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.20.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.20.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.20.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.20.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.20.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.20.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.20.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.20.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.20.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.20.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.20.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.20.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.22.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.22.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.22.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.22.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.22.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.22.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.22.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.22.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.22.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.22.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.22.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.22.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.4-1.sl4-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELsmp-0.4-1.sl4-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELsmp","version","0.4-1.sl4","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.4.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.4.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.4.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.0.7.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.0.7.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.0.7.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.EL-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.EL-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.EL","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELlargesmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELlargesmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELlargesmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELsmp-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELsmp-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELsmp","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELxenU-0.1-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELxenU-0.1-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELxenU","version","0.1-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-67.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-67.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-67.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1.sl4-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1.sl4-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.EL","version","0.4-1.sl4","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1.sl5-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.EL-0.4-1.sl5-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.EL","version","0.4-1.sl5","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.1.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.1.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.1.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.13.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.13.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.13.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.13.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.13.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.13.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.13.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.13.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.13.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.13.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.13.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.13.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.17.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.17.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.17.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.17.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.17.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.17.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.17.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.17.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.17.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.17.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.17.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.17.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.22.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.22.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.22.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.22.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.22.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.22.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.22.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.22.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.22.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.22.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.22.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.22.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.24.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.24.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.24.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.24.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.24.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.24.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.24.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.24.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.24.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.24.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.24.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.24.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.25.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.25.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.25.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.25.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.25.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.25.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.25.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.25.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.25.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.25.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.25.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.25.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.5.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.5.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.5.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.5.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.5.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.5.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.5.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.5.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.5.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.5.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.5.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.5.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.8.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.8.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.8.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.8.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.8.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.8.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.8.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.8.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.8.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.0.8.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.0.8.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.0.8.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-78.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-78.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-78.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.3.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.3.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.3.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.3.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.3.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.3.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.3.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.3.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.3.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.3.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.3.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.3.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.7.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.7.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.7.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.7.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.7.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.7.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.7.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.7.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.7.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.7.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.7.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.7.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.9.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.9.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.9.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.9.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.9.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.9.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.9.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.9.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.9.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.0.9.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.0.9.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.0.9.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.EL-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.EL-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.EL","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.ELlargesmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.ELlargesmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.ELlargesmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.ELsmp-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.ELsmp-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.ELsmp","version","0.4-1","arch","x86_64"),
# pkg = kernel-module-xfs-2.6.9-89.ELxenU-0.4-1-x86_64
escape("kernel-module-xfs-2.6.9-89.ELxenU-0.4-1-x86_64"),nlist("name","kernel-module-xfs-2.6.9-89.ELxenU","version","0.4-1","arch","x86_64"),
# pkg = lgtoclnt-7.4.4-1-x86_64
escape("lgtoclnt-7.4.4-1-x86_64"),nlist("name","lgtoclnt","version","7.4.4-1","arch","x86_64"),
# pkg = lgtofr-7.4.4-1-x86_64
escape("lgtofr-7.4.4-1-x86_64"),nlist("name","lgtofr","version","7.4.4-1","arch","x86_64"),
# pkg = lgtoja-7.4.4-1-x86_64
escape("lgtoja-7.4.4-1-x86_64"),nlist("name","lgtoja","version","7.4.4-1","arch","x86_64"),
# pkg = lgtoko-7.4.4-1-x86_64
escape("lgtoko-7.4.4-1-x86_64"),nlist("name","lgtoko","version","7.4.4-1","arch","x86_64"),
# pkg = lgtolicm-7.4.4-1-x86_64
escape("lgtolicm-7.4.4-1-x86_64"),nlist("name","lgtolicm","version","7.4.4-1","arch","x86_64"),
# pkg = lgtoman-7.4.4-1-x86_64
escape("lgtoman-7.4.4-1-x86_64"),nlist("name","lgtoman","version","7.4.4-1","arch","x86_64"),
# pkg = lgtonmc-3.4.4-1-i686
escape("lgtonmc-3.4.4-1-i686"),nlist("name","lgtonmc","version","3.4.4-1","arch","i686"),
# pkg = lgtonode-7.4.4-1-x86_64
escape("lgtonode-7.4.4-1-x86_64"),nlist("name","lgtonode","version","7.4.4-1","arch","x86_64"),
# pkg = lgtoserv-7.4.4-1-x86_64
escape("lgtoserv-7.4.4-1-x86_64"),nlist("name","lgtoserv","version","7.4.4-1","arch","x86_64"),
# pkg = lgtozh-7.4.4-1-x86_64
escape("lgtozh-7.4.4-1-x86_64"),nlist("name","lgtozh","version","7.4.4-1","arch","x86_64"),
# pkg = mod_fastcgi-2.4.3-1.slc4-x86_64
escape("mod_fastcgi-2.4.3-1.slc4-x86_64"),nlist("name","mod_fastcgi","version","2.4.3-1.slc4","arch","x86_64"),
# pkg = modules-myri10ge-2.6.9-67.0.4.ELlargesmp-1-1-x86_64
escape("modules-myri10ge-2.6.9-67.0.4.ELlargesmp-1-1-x86_64"),nlist("name","modules-myri10ge-2.6.9-67.0.4.ELlargesmp","version","1-1","arch","x86_64"),
# pkg = modules-myri10ge-2.6.9-89.0.16.ELlargesmp-1-1-x86_64
escape("modules-myri10ge-2.6.9-89.0.16.ELlargesmp-1-1-x86_64"),nlist("name","modules-myri10ge-2.6.9-89.0.16.ELlargesmp","version","1-1","arch","x86_64"),
# pkg = modules-myri10ge-2.6.9-89.0.9.ELlargesmp-1-1-x86_64
escape("modules-myri10ge-2.6.9-89.0.9.ELlargesmp-1-1-x86_64"),nlist("name","modules-myri10ge-2.6.9-89.0.9.ELlargesmp","version","1-1","arch","x86_64"),
# pkg = mptlinux-3.16.00.00-2.6.9_67.0.4.ELlargesmp-x86_64
escape("mptlinux-3.16.00.00-2.6.9_67.0.4.ELlargesmp-x86_64"),nlist("name","mptlinux","version","3.16.00.00-2.6.9_67.0.4.ELlargesmp","arch","x86_64"),
# pkg = mptlinux-redhat4.0-3.16.00.00-1-x86_64
escape("mptlinux-redhat4.0-3.16.00.00-1-x86_64"),nlist("name","mptlinux-redhat4.0","version","3.16.00.00-1","arch","x86_64"),
# pkg = multitail-5.2.2-1-x86_64
escape("multitail-5.2.2-1-x86_64"),nlist("name","multitail","version","5.2.2-1","arch","x86_64"),
# pkg = multitail-debuginfo-5.2.2-1-x86_64
escape("multitail-debuginfo-5.2.2-1-x86_64"),nlist("name","multitail-debuginfo","version","5.2.2-1","arch","x86_64"),
# pkg = nagios-3.0.3-1-x86_64
escape("nagios-3.0.3-1-x86_64"),nlist("name","nagios","version","3.0.3-1","arch","x86_64"),
# pkg = nagios-3.0.4-1-x86_64
escape("nagios-3.0.4-1-x86_64"),nlist("name","nagios","version","3.0.4-1","arch","x86_64"),
# pkg = nagios-3.0.5-1-x86_64
escape("nagios-3.0.5-1-x86_64"),nlist("name","nagios","version","3.0.5-1","arch","x86_64"),
# pkg = nagios-3.1.0-1-x86_64
escape("nagios-3.1.0-1-x86_64"),nlist("name","nagios","version","3.1.0-1","arch","x86_64"),
# pkg = nagios-debuginfo-3.0.3-1-x86_64
escape("nagios-debuginfo-3.0.3-1-x86_64"),nlist("name","nagios-debuginfo","version","3.0.3-1","arch","x86_64"),
# pkg = nagios-debuginfo-3.0.4-1-x86_64
escape("nagios-debuginfo-3.0.4-1-x86_64"),nlist("name","nagios-debuginfo","version","3.0.4-1","arch","x86_64"),
# pkg = nagios-debuginfo-3.0.5-1-x86_64
escape("nagios-debuginfo-3.0.5-1-x86_64"),nlist("name","nagios-debuginfo","version","3.0.5-1","arch","x86_64"),
# pkg = nagios-debuginfo-3.1.0-1-x86_64
escape("nagios-debuginfo-3.1.0-1-x86_64"),nlist("name","nagios-debuginfo","version","3.1.0-1","arch","x86_64"),
# pkg = nagios-devel-3.0.3-1-x86_64
escape("nagios-devel-3.0.3-1-x86_64"),nlist("name","nagios-devel","version","3.0.3-1","arch","x86_64"),
# pkg = nagios-devel-3.0.4-1-x86_64
escape("nagios-devel-3.0.4-1-x86_64"),nlist("name","nagios-devel","version","3.0.4-1","arch","x86_64"),
# pkg = nagios-devel-3.0.5-1-x86_64
escape("nagios-devel-3.0.5-1-x86_64"),nlist("name","nagios-devel","version","3.0.5-1","arch","x86_64"),
# pkg = nagios-devel-3.1.0-1-x86_64
escape("nagios-devel-3.1.0-1-x86_64"),nlist("name","nagios-devel","version","3.1.0-1","arch","x86_64"),
# pkg = nagios-plugins-1.4.13-1-x86_64
escape("nagios-plugins-1.4.13-1-x86_64"),nlist("name","nagios-plugins","version","1.4.13-1","arch","x86_64"),
# pkg = nagios-plugins-debuginfo-1.4.13-1-x86_64
escape("nagios-plugins-debuginfo-1.4.13-1-x86_64"),nlist("name","nagios-plugins-debuginfo","version","1.4.13-1","arch","x86_64"),
# pkg = nagios-www-3.0.3-1-x86_64
escape("nagios-www-3.0.3-1-x86_64"),nlist("name","nagios-www","version","3.0.3-1","arch","x86_64"),
# pkg = nagios-www-3.0.4-1-x86_64
escape("nagios-www-3.0.4-1-x86_64"),nlist("name","nagios-www","version","3.0.4-1","arch","x86_64"),
# pkg = nagios-www-3.0.5-1-x86_64
escape("nagios-www-3.0.5-1-x86_64"),nlist("name","nagios-www","version","3.0.5-1","arch","x86_64"),
# pkg = nagios-www-3.1.0-1-x86_64
escape("nagios-www-3.1.0-1-x86_64"),nlist("name","nagios-www","version","3.1.0-1","arch","x86_64"),
# pkg = nagiosgraph-1.2.1-1-x86_64
escape("nagiosgraph-1.2.1-1-x86_64"),nlist("name","nagiosgraph","version","1.2.1-1","arch","x86_64"),
# pkg = nagiosgraph-debuginfo-1.2.1-1-x86_64
escape("nagiosgraph-debuginfo-1.2.1-1-x86_64"),nlist("name","nagiosgraph-debuginfo","version","1.2.1-1","arch","x86_64"),
# pkg = nrpe-2.12-1-x86_64
escape("nrpe-2.12-1-x86_64"),nlist("name","nrpe","version","2.12-1","arch","x86_64"),
# pkg = nrpe-debuginfo-2.12-1-x86_64
escape("nrpe-debuginfo-2.12-1-x86_64"),nlist("name","nrpe-debuginfo","version","2.12-1","arch","x86_64"),
# pkg = nrpe-plugin-2.12-1-x86_64
escape("nrpe-plugin-2.12-1-x86_64"),nlist("name","nrpe-plugin","version","2.12-1","arch","x86_64"),
# pkg = perl-Apache-Admin-Config-0.94-1.el4.rf-noarch
escape("perl-Apache-Admin-Config-0.94-1.el4.rf-noarch"),nlist("name","perl-Apache-Admin-Config","version","0.94-1.el4.rf","arch","noarch"),
# pkg = perl-Config-IniFiles-2.39-6.el4-noarch
escape("perl-Config-IniFiles-2.39-6.el4-noarch"),nlist("name","perl-Config-IniFiles","version","2.39-6.el4","arch","noarch"),
# pkg = perl-Crypt-DES-2.05-3.2-x86_64
escape("perl-Crypt-DES-2.05-3.2-x86_64"),nlist("name","perl-Crypt-DES","version","2.05-3.2","arch","x86_64"),
# pkg = perl-Crypt-DES-debuginfo-2.05-3.2-x86_64
escape("perl-Crypt-DES-debuginfo-2.05-3.2-x86_64"),nlist("name","perl-Crypt-DES-debuginfo","version","2.05-3.2","arch","x86_64"),
# pkg = perl-DBI-1.607-1.el4.rf-x86_64
escape("perl-DBI-1.607-1.el4.rf-x86_64"),nlist("name","perl-DBI","version","1.607-1.el4.rf","arch","x86_64"),
# pkg = perl-HTML-Parser-3.59-1.el4.rf-x86_64
escape("perl-HTML-Parser-3.59-1.el4.rf-x86_64"),nlist("name","perl-HTML-Parser","version","3.59-1.el4.rf","arch","x86_64"),
# pkg = perl-HTML-Tagset-3.20-1.el4.rf-noarch
escape("perl-HTML-Tagset-3.20-1.el4.rf-noarch"),nlist("name","perl-HTML-Tagset","version","3.20-1.el4.rf","arch","noarch"),
# pkg = perl-MailTools-2.02-1.el4.rf-noarch
escape("perl-MailTools-2.02-1.el4.rf-noarch"),nlist("name","perl-MailTools","version","2.02-1.el4.rf","arch","noarch"),
# pkg = perl-Net-Daemon-0.43-1.el4.rf-noarch
escape("perl-Net-Daemon-0.43-1.el4.rf-noarch"),nlist("name","perl-Net-Daemon","version","0.43-1.el4.rf","arch","noarch"),
# pkg = perl-Net-SNMP-5.2.0-1.2-noarch
escape("perl-Net-SNMP-5.2.0-1.2-noarch"),nlist("name","perl-Net-SNMP","version","5.2.0-1.2","arch","noarch"),
# pkg = perl-PlRPC-0.2020-1.el4.rf-noarch
escape("perl-PlRPC-0.2020-1.el4.rf-noarch"),nlist("name","perl-PlRPC","version","0.2020-1.el4.rf","arch","noarch"),
# pkg = perl-Socket6-0.22-1-x86_64
escape("perl-Socket6-0.22-1-x86_64"),nlist("name","perl-Socket6","version","0.22-1","arch","x86_64"),
# pkg = perl-Socket6-debuginfo-0.22-1-x86_64
escape("perl-Socket6-debuginfo-0.22-1-x86_64"),nlist("name","perl-Socket6-debuginfo","version","0.22-1","arch","x86_64"),
# pkg = perl-TermReadKey-2.30-1.el4.rf-x86_64
escape("perl-TermReadKey-2.30-1.el4.rf-x86_64"),nlist("name","perl-TermReadKey","version","2.30-1.el4.rf","arch","x86_64"),
# pkg = perl-TermReadKey-2.30-3.el4.rf-x86_64
escape("perl-TermReadKey-2.30-3.el4.rf-x86_64"),nlist("name","perl-TermReadKey","version","2.30-3.el4.rf","arch","x86_64"),
# pkg = qt4-4.3.2-3.el4.pp-i386
escape("qt4-4.3.2-3.el4.pp-i386"),nlist("name","qt4","version","4.3.2-3.el4.pp","arch","i386"),
# pkg = qt4-4.3.2-3.el4.pp-x86_64
escape("qt4-4.3.2-3.el4.pp-x86_64"),nlist("name","qt4","version","4.3.2-3.el4.pp","arch","x86_64"),
# pkg = qt4-devel-4.3.2-3.el4.pp-i386
escape("qt4-devel-4.3.2-3.el4.pp-i386"),nlist("name","qt4-devel","version","4.3.2-3.el4.pp","arch","i386"),
# pkg = qt4-devel-4.3.2-3.el4.pp-x86_64
escape("qt4-devel-4.3.2-3.el4.pp-x86_64"),nlist("name","qt4-devel","version","4.3.2-3.el4.pp","arch","x86_64"),
# pkg = rdesktop-1.5.0-0.el4.rf-x86_64
escape("rdesktop-1.5.0-0.el4.rf-x86_64"),nlist("name","rdesktop","version","1.5.0-0.el4.rf","arch","x86_64"),
# pkg = rrdtool-1.2.27-5-x86_64
escape("rrdtool-1.2.27-5-x86_64"),nlist("name","rrdtool","version","1.2.27-5","arch","x86_64"),
# pkg = rrdtool-debuginfo-1.2.27-5-x86_64
escape("rrdtool-debuginfo-1.2.27-5-x86_64"),nlist("name","rrdtool-debuginfo","version","1.2.27-5","arch","x86_64"),
# pkg = rrdtool-devel-1.2.27-5-x86_64
escape("rrdtool-devel-1.2.27-5-x86_64"),nlist("name","rrdtool-devel","version","1.2.27-5","arch","x86_64"),
# pkg = rrdtool-doc-1.2.27-5-x86_64
escape("rrdtool-doc-1.2.27-5-x86_64"),nlist("name","rrdtool-doc","version","1.2.27-5","arch","x86_64"),
# pkg = rrdtool-perl-1.2.27-5-x86_64
escape("rrdtool-perl-1.2.27-5-x86_64"),nlist("name","rrdtool-perl","version","1.2.27-5","arch","x86_64"),
# pkg = rrdtool-python-1.2.27-5-x86_64
escape("rrdtool-python-1.2.27-5-x86_64"),nlist("name","rrdtool-python","version","1.2.27-5","arch","x86_64"),
# pkg = squid-3.0.STABLE10-1-x86_64
escape("squid-3.0.STABLE10-1-x86_64"),nlist("name","squid","version","3.0.STABLE10-1","arch","x86_64"),
# pkg = squid-debuginfo-3.0.STABLE10-1-x86_64
escape("squid-debuginfo-3.0.STABLE10-1-x86_64"),nlist("name","squid-debuginfo","version","3.0.STABLE10-1","arch","x86_64"),
# pkg = subversion-1.4.4-1-x86_64
escape("subversion-1.4.4-1-x86_64"),nlist("name","subversion","version","1.4.4-1","arch","x86_64"),
# pkg = xfs-0.4-1-x86_64
escape("xfs-0.4-1-x86_64"),nlist("name","xfs","version","0.4-1","arch","x86_64"),
# pkg = xfs-debuginfo-0.4-1-x86_64
escape("xfs-debuginfo-0.4-1-x86_64"),nlist("name","xfs-debuginfo","version","0.4-1","arch","x86_64"),
# pkg = xfsdump-2.2.21-1.SL-x86_64
escape("xfsdump-2.2.21-1.SL-x86_64"),nlist("name","xfsdump","version","2.2.21-1.SL","arch","x86_64"),
# pkg = xfsdump-2.2.46-1-x86_64
escape("xfsdump-2.2.46-1-x86_64"),nlist("name","xfsdump","version","2.2.46-1","arch","x86_64"),
# pkg = xfsdump-debuginfo-2.2.46-1-x86_64
escape("xfsdump-debuginfo-2.2.46-1-x86_64"),nlist("name","xfsdump-debuginfo","version","2.2.46-1","arch","x86_64"),
# pkg = xfsprogs-2.6.13-1.SL-x86_64
escape("xfsprogs-2.6.13-1.SL-x86_64"),nlist("name","xfsprogs","version","2.6.13-1.SL","arch","x86_64"),
# pkg = xfsprogs-2.9.4-1-x86_64
escape("xfsprogs-2.9.4-1-x86_64"),nlist("name","xfsprogs","version","2.9.4-1","arch","x86_64"),
# pkg = xfsprogs-debuginfo-2.9.4-1-x86_64
escape("xfsprogs-debuginfo-2.9.4-1-x86_64"),nlist("name","xfsprogs-debuginfo","version","2.9.4-1","arch","x86_64"),
# pkg = xfsprogs-devel-2.6.13-1.SL-x86_64
escape("xfsprogs-devel-2.6.13-1.SL-x86_64"),nlist("name","xfsprogs-devel","version","2.6.13-1.SL","arch","x86_64"),
# pkg = xfsprogs-devel-2.9.4-1-x86_64
escape("xfsprogs-devel-2.9.4-1-x86_64"),nlist("name","xfsprogs-devel","version","2.9.4-1","arch","x86_64"),
# pkg = yum-3.2.19-3-noarch
escape("yum-3.2.19-3-noarch"),nlist("name","yum","version","3.2.19-3","arch","noarch"),
);
