#
# Generated by RepositoryTask on 4/3/12 7:59 PM
#
# name = sl570_i386_updates
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/os/sl570-i386/updates/
#

structure template repository/sl570_i386_updates;

"name" = "sl570_i386_updates";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/os/sl570-i386/updates/")
);

"contents" = nlist(
);
