#
# Generated by RepositoryTask on 5/22/13 1:00 PM
#
# name = sl590_x86_64_updates
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/os/sl590-x86_64/updates/
#

structure template repository/sl590_x86_64_updates;

"name" = "sl590_x86_64_updates";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/os/sl590-x86_64/updates/")
);

"contents" = nlist(
);
