#
# Generated by RepositoryTask on 3/26/13 10:07 AM
#
# name = sl5_internet2
# owner = grid.support@lal.in2p3.fr
# url = http://quattor.web.lal.in2p3.fr/packages/os/sl5/internet2
#

structure template repository/sl5_internet2;

"name" = "sl5_internet2";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url","http://quattor.web.lal.in2p3.fr/packages/os/sl5/internet2")
);

"contents" = nlist(
# pkg = I2util-1.1-1-i386
escape("I2util-1.1-1-i386"),nlist("name","I2util","version","1.1-1","arch","i386"),
# pkg = Internet2-repo-0.2-1-noarch
escape("Internet2-repo-0.2-1-noarch"),nlist("name","Internet2-repo","version","0.2-1","arch","noarch"),
# pkg = Internet2-repo-0.2-2-noarch
escape("Internet2-repo-0.2-2-noarch"),nlist("name","Internet2-repo","version","0.2-2","arch","noarch"),
# pkg = Internet2-repo-0.2-3-noarch
escape("Internet2-repo-0.2-3-noarch"),nlist("name","Internet2-repo","version","0.2-3","arch","noarch"),
# pkg = Internet2-repo-0.2-4-noarch
escape("Internet2-repo-0.2-4-noarch"),nlist("name","Internet2-repo","version","0.2-4","arch","noarch"),
# pkg = Internet2-repo-0.2-5-noarch
escape("Internet2-repo-0.2-5-noarch"),nlist("name","Internet2-repo","version","0.2-5","arch","noarch"),
# pkg = Internet2-repo-0.2-6-noarch
escape("Internet2-repo-0.2-6-noarch"),nlist("name","Internet2-repo","version","0.2-6","arch","noarch"),
# pkg = Internet2-repo-0.2-7-noarch
escape("Internet2-repo-0.2-7-noarch"),nlist("name","Internet2-repo","version","0.2-7","arch","noarch"),
# pkg = Internet2-repo-0.2-8-noarch
escape("Internet2-repo-0.2-8-noarch"),nlist("name","Internet2-repo","version","0.2-8","arch","noarch"),
# pkg = bwctl-1.4-1-i386
escape("bwctl-1.4-1-i386"),nlist("name","bwctl","version","1.4-1","arch","i386"),
# pkg = bwctl-client-1.3-5-i386
escape("bwctl-client-1.3-5-i386"),nlist("name","bwctl-client","version","1.3-5","arch","i386"),
# pkg = bwctl-client-1.4-1-i386
escape("bwctl-client-1.4-1-i386"),nlist("name","bwctl-client","version","1.4-1","arch","i386"),
# pkg = bwctl-debuginfo-1.4-1-i386
escape("bwctl-debuginfo-1.4-1-i386"),nlist("name","bwctl-debuginfo","version","1.4-1","arch","i386"),
# pkg = bwctl-devel-1.4-1-i386
escape("bwctl-devel-1.4-1-i386"),nlist("name","bwctl-devel","version","1.4-1","arch","i386"),
# pkg = bwctl-server-1.3-5-i386
escape("bwctl-server-1.3-5-i386"),nlist("name","bwctl-server","version","1.3-5","arch","i386"),
# pkg = bwctl-server-1.4-1-i386
escape("bwctl-server-1.4-1-i386"),nlist("name","bwctl-server","version","1.4-1","arch","i386"),
# pkg = dbxml-2.3.11-1.pSPS-i386
escape("dbxml-2.3.11-1.pSPS-i386"),nlist("name","dbxml","version","2.3.11-1.pSPS","arch","i386"),
# pkg = dbxml-devel-2.3.11-1.pSPS-i386
escape("dbxml-devel-2.3.11-1.pSPS-i386"),nlist("name","dbxml-devel","version","2.3.11-1.pSPS","arch","i386"),
# pkg = dbxml-doc-2.3.11-1.pSPS-i386
escape("dbxml-doc-2.3.11-1.pSPS-i386"),nlist("name","dbxml-doc","version","2.3.11-1.pSPS","arch","i386"),
# pkg = kernel-2.6.18-308.1.1.el5.web100-i686
escape("kernel-2.6.18-308.1.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.1.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.13.1.el5.web100-i686
escape("kernel-2.6.18-308.13.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.13.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.16.1.el5.web100-i686
escape("kernel-2.6.18-308.16.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.16.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.20.1.el5.web100-i686
escape("kernel-2.6.18-308.20.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.20.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.24.1.el5.web100-i686
escape("kernel-2.6.18-308.24.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.24.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.4.1.el5.web100-i686
escape("kernel-2.6.18-308.4.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.4.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.8.1.el5.web100-i686
escape("kernel-2.6.18-308.8.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.8.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-308.8.2.el5.web100-i686
escape("kernel-2.6.18-308.8.2.el5.web100-i686"),nlist("name","kernel","version","2.6.18-308.8.2.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-348.1.1.el5.web100-i686
escape("kernel-2.6.18-348.1.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-348.1.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-348.2.1.el5.web100-i686
escape("kernel-2.6.18-348.2.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-348.2.1.el5.web100","arch","i686"),
# pkg = kernel-2.6.18-348.3.1.el5.web100-i686
escape("kernel-2.6.18-348.3.1.el5.web100-i686"),nlist("name","kernel","version","2.6.18-348.3.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.1.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.1.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.1.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.13.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.13.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.13.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.16.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.16.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.16.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.20.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.20.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.20.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.24.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.24.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.24.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.4.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.4.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.4.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.8.1.el5.web100-i686
escape("kernel-devel-2.6.18-308.8.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.8.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-308.8.2.el5.web100-i686
escape("kernel-devel-2.6.18-308.8.2.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-308.8.2.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-348.1.1.el5.web100-i686
escape("kernel-devel-2.6.18-348.1.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-348.1.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-348.2.1.el5.web100-i686
escape("kernel-devel-2.6.18-348.2.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-348.2.1.el5.web100","arch","i686"),
# pkg = kernel-devel-2.6.18-348.3.1.el5.web100-i686
escape("kernel-devel-2.6.18-348.3.1.el5.web100-i686"),nlist("name","kernel-devel","version","2.6.18-348.3.1.el5.web100","arch","i686"),
# pkg = kernel-headers-2.6.18-308.1.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.1.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.1.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.13.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.13.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.13.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.16.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.16.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.16.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.20.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.20.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.20.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.24.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.24.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.24.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.4.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.4.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.4.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.8.1.el5.web100-i386
escape("kernel-headers-2.6.18-308.8.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.8.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-308.8.2.el5.web100-i386
escape("kernel-headers-2.6.18-308.8.2.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-308.8.2.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-348.1.1.el5.web100-i386
escape("kernel-headers-2.6.18-348.1.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-348.1.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-348.2.1.el5.web100-i386
escape("kernel-headers-2.6.18-348.2.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-348.2.1.el5.web100","arch","i386"),
# pkg = kernel-headers-2.6.18-348.3.1.el5.web100-i386
escape("kernel-headers-2.6.18-348.3.1.el5.web100-i386"),nlist("name","kernel-headers","version","2.6.18-348.3.1.el5.web100","arch","i386"),
# pkg = kmod-sk98lin-10.85.9.3-1.el5-i686
escape("kmod-sk98lin-10.85.9.3-1.el5-i686"),nlist("name","kmod-sk98lin","version","10.85.9.3-1.el5","arch","i686"),
# pkg = lookup-service-0.1-3-noarch
escape("lookup-service-0.1-3-noarch"),nlist("name","lookup-service","version","0.1-3","arch","noarch"),
# pkg = maddash-1.0-2-noarch
escape("maddash-1.0-2-noarch"),nlist("name","maddash","version","1.0-2","arch","noarch"),
# pkg = maddash-server-1.0-5-noarch
escape("maddash-server-1.0-5-noarch"),nlist("name","maddash-server","version","1.0-5","arch","noarch"),
# pkg = maddash-webui-1.0-2-noarch
escape("maddash-webui-1.0-2-noarch"),nlist("name","maddash-webui","version","1.0-2","arch","noarch"),
# pkg = ndt-3.4.4a-4.el5-i386
escape("ndt-3.4.4a-4.el5-i386"),nlist("name","ndt","version","3.4.4a-4.el5","arch","i386"),
# pkg = ndt-3.6.4-2.pSPS-i386
escape("ndt-3.6.4-2.pSPS-i386"),nlist("name","ndt","version","3.6.4-2.pSPS","arch","i386"),
# pkg = ndt-3.6.4-3.el5.centos-i386
escape("ndt-3.6.4-3.el5.centos-i386"),nlist("name","ndt","version","3.6.4-3.el5.centos","arch","i386"),
# pkg = ndt-3.6.5-1.el5.centos-i386
escape("ndt-3.6.5-1.el5.centos-i386"),nlist("name","ndt","version","3.6.5-1.el5.centos","arch","i386"),
# pkg = ndt-3.6.5.1-1.el5.centos-i686
escape("ndt-3.6.5.1-1.el5.centos-i686"),nlist("name","ndt","version","3.6.5.1-1.el5.centos","arch","i686"),
# pkg = ndt-client-3.6.4-1.pSPS-i386
escape("ndt-client-3.6.4-1.pSPS-i386"),nlist("name","ndt-client","version","3.6.4-1.pSPS","arch","i386"),
# pkg = ndt-client-3.6.4-2.pSPS-i386
escape("ndt-client-3.6.4-2.pSPS-i386"),nlist("name","ndt-client","version","3.6.4-2.pSPS","arch","i386"),
# pkg = ndt-client-3.6.4-3.el5.centos-i386
escape("ndt-client-3.6.4-3.el5.centos-i386"),nlist("name","ndt-client","version","3.6.4-3.el5.centos","arch","i386"),
# pkg = ndt-client-3.6.5-1.el5.centos-i386
escape("ndt-client-3.6.5-1.el5.centos-i386"),nlist("name","ndt-client","version","3.6.5-1.el5.centos","arch","i386"),
# pkg = ndt-client-3.6.5.1-1.el5.centos-i686
escape("ndt-client-3.6.5.1-1.el5.centos-i686"),nlist("name","ndt-client","version","3.6.5.1-1.el5.centos","arch","i686"),
# pkg = ndt-server-3.6.4-1.pSPS-i386
escape("ndt-server-3.6.4-1.pSPS-i386"),nlist("name","ndt-server","version","3.6.4-1.pSPS","arch","i386"),
# pkg = ndt-server-3.6.4-2.pSPS-i386
escape("ndt-server-3.6.4-2.pSPS-i386"),nlist("name","ndt-server","version","3.6.4-2.pSPS","arch","i386"),
# pkg = ndt-server-3.6.4-3.el5.centos-i386
escape("ndt-server-3.6.4-3.el5.centos-i386"),nlist("name","ndt-server","version","3.6.4-3.el5.centos","arch","i386"),
# pkg = ndt-server-3.6.5-1.el5.centos-i386
escape("ndt-server-3.6.5-1.el5.centos-i386"),nlist("name","ndt-server","version","3.6.5-1.el5.centos","arch","i386"),
# pkg = ndt-server-3.6.5.1-1.el5.centos-i686
escape("ndt-server-3.6.5.1-1.el5.centos-i686"),nlist("name","ndt-server","version","3.6.5.1-1.el5.centos","arch","i686"),
# pkg = npad-1.5.6-1.el5-i386
escape("npad-1.5.6-1.el5-i386"),nlist("name","npad","version","1.5.6-1.el5","arch","i386"),
# pkg = npad-1.5.6-2.el5-i386
escape("npad-1.5.6-2.el5-i386"),nlist("name","npad","version","1.5.6-2.el5","arch","i386"),
# pkg = nuttcp-6.1.2-1-i386
escape("nuttcp-6.1.2-1-i386"),nlist("name","nuttcp","version","6.1.2-1","arch","i386"),
# pkg = oscars-0.6-1-noarch
escape("oscars-0.6-1-noarch"),nlist("name","oscars","version","0.6-1","arch","noarch"),
# pkg = oscars-0.6-2-noarch
escape("oscars-0.6-2-noarch"),nlist("name","oscars","version","0.6-2","arch","noarch"),
# pkg = oscars-api-0.6-8-noarch
escape("oscars-api-0.6-8-noarch"),nlist("name","oscars-api","version","0.6-8","arch","noarch"),
# pkg = oscars-api-0.6-9-noarch
escape("oscars-api-0.6-9-noarch"),nlist("name","oscars-api","version","0.6-9","arch","noarch"),
# pkg = oscars-authN-0.6-1-noarch
escape("oscars-authN-0.6-1-noarch"),nlist("name","oscars-authN","version","0.6-1","arch","noarch"),
# pkg = oscars-authZ-0.6-1-noarch
escape("oscars-authZ-0.6-1-noarch"),nlist("name","oscars-authZ","version","0.6-1","arch","noarch"),
# pkg = oscars-authZ-0.6-2-noarch
escape("oscars-authZ-0.6-2-noarch"),nlist("name","oscars-authZ","version","0.6-2","arch","noarch"),
# pkg = oscars-coordinator-0.6-1-noarch
escape("oscars-coordinator-0.6-1-noarch"),nlist("name","oscars-coordinator","version","0.6-1","arch","noarch"),
# pkg = oscars-env-0.6-1-noarch
escape("oscars-env-0.6-1-noarch"),nlist("name","oscars-env","version","0.6-1","arch","noarch"),
# pkg = oscars-ionservlets-0.6-3-noarch
escape("oscars-ionservlets-0.6-3-noarch"),nlist("name","oscars-ionservlets","version","0.6-3","arch","noarch"),
# pkg = oscars-ionui-0.6-3-noarch
escape("oscars-ionui-0.6-3-noarch"),nlist("name","oscars-ionui","version","0.6-3","arch","noarch"),
# pkg = oscars-lookup-0.6-4-noarch
escape("oscars-lookup-0.6-4-noarch"),nlist("name","oscars-lookup","version","0.6-4","arch","noarch"),
# pkg = oscars-notificationBridge-0.6-1-noarch
escape("oscars-notificationBridge-0.6-1-noarch"),nlist("name","oscars-notificationBridge","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-bandwidth-0.6-1-noarch
escape("oscars-pce-bandwidth-0.6-1-noarch"),nlist("name","oscars-pce-bandwidth","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-connectivity-0.6-1-noarch
escape("oscars-pce-connectivity-0.6-1-noarch"),nlist("name","oscars-pce-connectivity","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-dijkstra-0.6-1-noarch
escape("oscars-pce-dijkstra-0.6-1-noarch"),nlist("name","oscars-pce-dijkstra","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-l3mpls-0.6-1-noarch
escape("oscars-pce-l3mpls-0.6-1-noarch"),nlist("name","oscars-pce-l3mpls","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-nullagg-0.6-1-noarch
escape("oscars-pce-nullagg-0.6-1-noarch"),nlist("name","oscars-pce-nullagg","version","0.6-1","arch","noarch"),
# pkg = oscars-pce-vlan-0.6-1-noarch
escape("oscars-pce-vlan-0.6-1-noarch"),nlist("name","oscars-pce-vlan","version","0.6-1","arch","noarch"),
# pkg = oscars-pss-bridge-0.6-1-noarch
escape("oscars-pss-bridge-0.6-1-noarch"),nlist("name","oscars-pss-bridge","version","0.6-1","arch","noarch"),
# pkg = oscars-pss-dragon-0.6-1-noarch
escape("oscars-pss-dragon-0.6-1-noarch"),nlist("name","oscars-pss-dragon","version","0.6-1","arch","noarch"),
# pkg = oscars-pss-eompls-0.6-3-noarch
escape("oscars-pss-eompls-0.6-3-noarch"),nlist("name","oscars-pss-eompls","version","0.6-3","arch","noarch"),
# pkg = oscars-pss-openflow-0.6-1-noarch
escape("oscars-pss-openflow-0.6-1-noarch"),nlist("name","oscars-pss-openflow","version","0.6-1","arch","noarch"),
# pkg = oscars-pss-stub-0.6-1-noarch
escape("oscars-pss-stub-0.6-1-noarch"),nlist("name","oscars-pss-stub","version","0.6-1","arch","noarch"),
# pkg = oscars-resourceManager-0.6-1-noarch
escape("oscars-resourceManager-0.6-1-noarch"),nlist("name","oscars-resourceManager","version","0.6-1","arch","noarch"),
# pkg = oscars-resourceManager-0.6-2-noarch
escape("oscars-resourceManager-0.6-2-noarch"),nlist("name","oscars-resourceManager","version","0.6-2","arch","noarch"),
# pkg = oscars-servlets-0.6-2-noarch
escape("oscars-servlets-0.6-2-noarch"),nlist("name","oscars-servlets","version","0.6-2","arch","noarch"),
# pkg = oscars-tools-0.6-3-noarch
escape("oscars-tools-0.6-3-noarch"),nlist("name","oscars-tools","version","0.6-3","arch","noarch"),
# pkg = oscars-topoBridge-0.6-1-noarch
escape("oscars-topoBridge-0.6-1-noarch"),nlist("name","oscars-topoBridge","version","0.6-1","arch","noarch"),
# pkg = oscars-wbui-0.6-2-noarch
escape("oscars-wbui-0.6-2-noarch"),nlist("name","oscars-wbui","version","0.6-2","arch","noarch"),
# pkg = oscars-wsnbroker-0.6-1-noarch
escape("oscars-wsnbroker-0.6-1-noarch"),nlist("name","oscars-wsnbroker","version","0.6-1","arch","noarch"),
# pkg = owamp-3.2rc4-1-i386
escape("owamp-3.2rc4-1-i386"),nlist("name","owamp","version","3.2rc4-1","arch","i386"),
# pkg = owamp-3.3-1-i386
escape("owamp-3.3-1-i386"),nlist("name","owamp","version","3.3-1","arch","i386"),
# pkg = owamp-3.3rc1-1-i386
escape("owamp-3.3rc1-1-i386"),nlist("name","owamp","version","3.3rc1-1","arch","i386"),
# pkg = owamp-client-3.2rc4-1-i386
escape("owamp-client-3.2rc4-1-i386"),nlist("name","owamp-client","version","3.2rc4-1","arch","i386"),
# pkg = owamp-client-3.3-1-i386
escape("owamp-client-3.3-1-i386"),nlist("name","owamp-client","version","3.3-1","arch","i386"),
# pkg = owamp-client-3.3rc1-1-i386
escape("owamp-client-3.3rc1-1-i386"),nlist("name","owamp-client","version","3.3rc1-1","arch","i386"),
# pkg = owamp-debuginfo-3.3-1-i386
escape("owamp-debuginfo-3.3-1-i386"),nlist("name","owamp-debuginfo","version","3.3-1","arch","i386"),
# pkg = owamp-server-3.2rc4-1-i386
escape("owamp-server-3.2rc4-1-i386"),nlist("name","owamp-server","version","3.2rc4-1","arch","i386"),
# pkg = owamp-server-3.3-1-i386
escape("owamp-server-3.3-1-i386"),nlist("name","owamp-server","version","3.3-1","arch","i386"),
# pkg = owamp-server-3.3rc1-1-i386
escape("owamp-server-3.3rc1-1-i386"),nlist("name","owamp-server","version","3.3rc1-1","arch","i386"),
# pkg = perl-AnyEvent-5.271-1.pSPS-noarch
escape("perl-AnyEvent-5.271-1.pSPS-noarch"),nlist("name","perl-AnyEvent","version","5.271-1.pSPS","arch","noarch"),
# pkg = perl-AnyEvent-HTTP-1.45-1.pSPS-noarch
escape("perl-AnyEvent-HTTP-1.45-1.pSPS-noarch"),nlist("name","perl-AnyEvent-HTTP","version","1.45-1.pSPS","arch","noarch"),
# pkg = perl-Apache-RPC-0.64-1.el5-noarch
escape("perl-Apache-RPC-0.64-1.el5-noarch"),nlist("name","perl-Apache-RPC","version","0.64-1.el5","arch","noarch"),
# pkg = perl-CGI-Ajax-0.707-1.el5-noarch
escape("perl-CGI-Ajax-0.707-1.el5-noarch"),nlist("name","perl-CGI-Ajax","version","0.707-1.el5","arch","noarch"),
# pkg = perl-Carp-Assert-0.20-3.el5-noarch
escape("perl-Carp-Assert-0.20-3.el5-noarch"),nlist("name","perl-Carp-Assert","version","0.20-3.el5","arch","noarch"),
# pkg = perl-Class-Fields-0.203-3.pSPS-noarch
escape("perl-Class-Fields-0.203-3.pSPS-noarch"),nlist("name","perl-Class-Fields","version","0.203-3.pSPS","arch","noarch"),
# pkg = perl-Clone-PP-1.02-1-noarch
escape("perl-Clone-PP-1.02-1-noarch"),nlist("name","perl-Clone-PP","version","1.02-1","arch","noarch"),
# pkg = perl-Data-HashArray-1.0-1-noarch
escape("perl-Data-HashArray-1.0-1-noarch"),nlist("name","perl-Data-HashArray","version","1.0-1","arch","noarch"),
# pkg = perl-Data-Validate-Domain-0.09-3.pSPS-noarch
escape("perl-Data-Validate-Domain-0.09-3.pSPS-noarch"),nlist("name","perl-Data-Validate-Domain","version","0.09-3.pSPS","arch","noarch"),
# pkg = perl-Data-Validate-IP-0.11-2.pSPS-noarch
escape("perl-Data-Validate-IP-0.11-2.pSPS-noarch"),nlist("name","perl-Data-Validate-IP","version","0.11-2.pSPS","arch","noarch"),
# pkg = perl-DateTime-Format-Pg-0.16001-2-noarch
escape("perl-DateTime-Format-Pg-0.16001-2-noarch"),nlist("name","perl-DateTime-Format-Pg","version","0.16001-2","arch","noarch"),
# pkg = perl-Hash-Merge-0.12-1.pSPS-noarch
escape("perl-Hash-Merge-0.12-1.pSPS-noarch"),nlist("name","perl-Hash-Merge","version","0.12-1.pSPS","arch","noarch"),
# pkg = perl-JSON-XS-2.24-2.el5-i386
escape("perl-JSON-XS-2.24-2.el5-i386"),nlist("name","perl-JSON-XS","version","2.24-2.el5","arch","i386"),
# pkg = perl-Math-Int64-0.09-2.pSPS-i386
escape("perl-Math-Int64-0.09-2.pSPS-i386"),nlist("name","perl-Math-Int64","version","0.09-2.pSPS","arch","i386"),
# pkg = perl-Net-CIDR-0.13-2.pSPS-noarch
escape("perl-Net-CIDR-0.13-2.pSPS-noarch"),nlist("name","perl-Net-CIDR","version","0.13-2.pSPS","arch","noarch"),
# pkg = perl-Net-Domain-TLD-1.68-1.el5-noarch
escape("perl-Net-Domain-TLD-1.68-1.el5-noarch"),nlist("name","perl-Net-Domain-TLD","version","1.68-1.el5","arch","noarch"),
# pkg = perl-Net-IPTrie-0.4-5.pSPS-noarch
escape("perl-Net-IPTrie-0.4-5.pSPS-noarch"),nlist("name","perl-Net-IPTrie","version","0.4-5.pSPS","arch","noarch"),
# pkg = perl-Net-Interface-1.012-1-i386
escape("perl-Net-Interface-1.012-1-i386"),nlist("name","perl-Net-Interface","version","1.012-1","arch","i386"),
# pkg = perl-Net-Ping-External-0.12-1.el5-noarch
escape("perl-Net-Ping-External-0.12-1.el5-noarch"),nlist("name","perl-Net-Ping-External","version","0.12-1.el5","arch","noarch"),
# pkg = perl-Net-Traceroute-1.13-1-noarch
escape("perl-Net-Traceroute-1.13-1-noarch"),nlist("name","perl-Net-Traceroute","version","1.13-1","arch","noarch"),
# pkg = perl-NetAddr-IP-4.027-2.pSPS-i386
escape("perl-NetAddr-IP-4.027-2.pSPS-i386"),nlist("name","perl-NetAddr-IP","version","4.027-2.pSPS","arch","i386"),
# pkg = perl-PlRPC-0.2020-1.el5-noarch
escape("perl-PlRPC-0.2020-1.el5-noarch"),nlist("name","perl-PlRPC","version","0.2020-1.el5","arch","noarch"),
# pkg = perl-RPC-XML-0.64-1.el5-noarch
escape("perl-RPC-XML-0.64-1.el5-noarch"),nlist("name","perl-RPC-XML","version","0.64-1.el5","arch","noarch"),
# pkg = perl-Rose-DB-0.750-1-noarch
escape("perl-Rose-DB-0.750-1-noarch"),nlist("name","perl-Rose-DB","version","0.750-1","arch","noarch"),
# pkg = perl-Rose-DB-Object-0.780-1-noarch
escape("perl-Rose-DB-Object-0.780-1-noarch"),nlist("name","perl-Rose-DB-Object","version","0.780-1","arch","noarch"),
# pkg = perl-Rose-DateTime-0.532-1-noarch
escape("perl-Rose-DateTime-0.532-1-noarch"),nlist("name","perl-Rose-DateTime","version","0.532-1","arch","noarch"),
# pkg = perl-Rose-Object-0.855-1-noarch
escape("perl-Rose-Object-0.855-1-noarch"),nlist("name","perl-Rose-Object","version","0.855-1","arch","noarch"),
# pkg = perl-SQL-ReservedWords-0.7-1-noarch
escape("perl-SQL-ReservedWords-0.7-1-noarch"),nlist("name","perl-SQL-ReservedWords","version","0.7-1","arch","noarch"),
# pkg = perl-Sys-Syslog-0.27-2.pSPS-i386
escape("perl-Sys-Syslog-0.27-2.pSPS-i386"),nlist("name","perl-Sys-Syslog","version","0.27-2.pSPS","arch","i386"),
# pkg = perl-Time-Clock-0.12-1-noarch
escape("perl-Time-Clock-0.12-1-noarch"),nlist("name","perl-Time-Clock","version","0.12-1","arch","noarch"),
# pkg = perl-XML-LibXML-1.70-1.pSPS-i386
escape("perl-XML-LibXML-1.70-1.pSPS-i386"),nlist("name","perl-XML-LibXML","version","1.70-1.pSPS","arch","i386"),
# pkg = perl-XML-Pastor-1.0.3-1-noarch
escape("perl-XML-Pastor-1.0.3-1-noarch"),nlist("name","perl-XML-Pastor","version","1.0.3-1","arch","noarch"),
# pkg = perl-parent-0.221-2.el5-noarch
escape("perl-parent-0.221-2.el5-noarch"),nlist("name","perl-parent","version","0.221-2.el5","arch","noarch"),
# pkg = perl-perfSONAR_PS-CircuitMonitoring-GUI-3.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-CircuitMonitoring-GUI-3.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-CircuitMonitoring-GUI","version","3.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-CircuitMonitoring-MonitoringAgent-3.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-CircuitMonitoring-MonitoringAgent-3.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-CircuitMonitoring-MonitoringAgent","version","3.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-CircuitMonitoring-Shared-3.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-CircuitMonitoring-Shared-3.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-CircuitMonitoring-Shared","version","3.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSCacheDaemon-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-LSCacheDaemon-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSCacheDaemon","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LSRegistrationDaemon-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-LSRegistrationDaemon-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LSRegistrationDaemon","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LookupService-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LookupService-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LookupService-3.2.1-1.pSPS-src
escape("perl-perfSONAR_PS-LookupService-3.2.1-1.pSPS-src"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2.1-1.pSPS","arch","src"),
# pkg = perl-perfSONAR_PS-LookupService-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-LookupService-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LookupService-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-LookupService-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LookupService-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-LookupService-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-LookupService-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-LookupService-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-LookupService","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-5.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-8.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-8.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-8.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-3.2.2-9.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-3.2.2-9.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig","version","3.2.2-9.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-5.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-8.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-8.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-8.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-9.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Agent-3.2.2-9.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Agent","version","3.2.2-9.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-5.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-8.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-8.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-8.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-9.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-GUIAgent-3.2.2-9.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-GUIAgent","version","3.2.2-9.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-5.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-7.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-7.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-7.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-8.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-8.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-8.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-9.pSPS-noarch
escape("perl-perfSONAR_PS-MeshConfig-Shared-3.2.2-9.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-MeshConfig-Shared","version","3.2.2-9.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Nagios-3.2.2-5.pSPS-noarch
escape("perl-perfSONAR_PS-Nagios-3.2.2-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Nagios","version","3.2.2-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-GUI-3.1-11.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-3.1-11.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI","version","3.1-11.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-GUI-3.2.1-1.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-3.2.1-1.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI","version","3.2.1-1.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-GUI-3.2.1-2.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-3.2.1-2.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI","version","3.2.1-2.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-GUI-3.2.1-3.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-3.2.1-3.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI","version","3.2.1-3.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-GUI-3.2.2-1.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-3.2.2-1.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI","version","3.2.2-1.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-GUI-debuginfo-3.2.2-1.pSPS-i386
escape("perl-perfSONAR_PS-PingER-GUI-debuginfo-3.2.2-1.pSPS-i386"),nlist("name","perl-perfSONAR_PS-PingER-GUI-debuginfo","version","3.2.2-1.pSPS","arch","i386"),
# pkg = perl-perfSONAR_PS-PingER-server-3.1-13.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.1-13.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.1-13.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.1-14.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.1-14.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.1-14.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-PingER-server-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-PingER-server-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-PingER-server","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-SNMPMA-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-SNMPMA-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-SNMPMA","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Status-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-Status-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Status","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TL1Collector-3.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TL1Collector-3.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TL1Collector","version","3.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TL1Collector-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TL1Collector-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TL1Collector","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TL1Collector-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-TL1Collector-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TL1Collector","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TL1Collector-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-TL1Collector-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TL1Collector","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TL1Collector-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TL1Collector-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TL1Collector","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.1-5.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.1-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.1-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2-6.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-5.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.1-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.1-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-LiveCD-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-LiveCD","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-5.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.1-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.1-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-4.pSPS-noarch
escape("perl-perfSONAR_PS-Toolkit-SystemEnvironment-3.2.2-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-Toolkit-SystemEnvironment","version","3.2.2-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TopologyService-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-TopologyService-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TopologyService","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-client-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-client-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-client","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-config-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-config-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-config","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-TracerouteMA-server-3.2.2-3.pSPS-noarch
escape("perl-perfSONAR_PS-TracerouteMA-server-3.2.2-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-TracerouteMA-server","version","3.2.2-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfAdmin-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfAdmin-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfAdmin","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-client-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-client-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-client","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-config-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-config-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-config","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-perfSONARBUOY-server-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-perfSONARBUOY-server-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-perfSONARBUOY-server","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-1.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-2.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-2.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-3.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-3.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-3.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-4.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-4.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-4.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-5.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-5.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-5.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.1-6.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.1-6.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.1-6.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.2-1.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.2-1.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.2-1.pSPS","arch","noarch"),
# pkg = perl-perfSONAR_PS-serviceTest-3.2.2-2.pSPS-noarch
escape("perl-perfSONAR_PS-serviceTest-3.2.2-2.pSPS-noarch"),nlist("name","perl-perfSONAR_PS-serviceTest","version","3.2.2-2.pSPS","arch","noarch"),
# pkg = web100_userland-1.7-3.el5-i386
escape("web100_userland-1.7-3.el5-i386"),nlist("name","web100_userland","version","1.7-3.el5","arch","i386"),
# pkg = web100_userland-1.7-6.pSPS-i386
escape("web100_userland-1.7-6.pSPS-i386"),nlist("name","web100_userland","version","1.7-6.pSPS","arch","i386"),
# pkg = web100_userland-1.7-7.pSPS-i386
escape("web100_userland-1.7-7.pSPS-i386"),nlist("name","web100_userland","version","1.7-7.pSPS","arch","i386"),
);
