#!/usr/bin/env bash

set -e # halt script on error

echo GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
echo GITHUB_BASE_REF: ${GITHUB_BASE_REF}
echo GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}

# Retrieve last version of create-vanilla-SCDB from GitHub
echo "Downloading create-vanilla-SCDB from GitHub..."
rm -f /tmp/create-vanilla-SCDB.sh
wget -q https://raw.githubusercontent.com/quattor/scdb/master/utils/scdb/create-vanilla-SCDB.sh -O /tmp/create-vanilla-SCDB.sh
chmod u+x /tmp/create-vanilla-SCDB.sh

/tmp/create-vanilla-SCDB.sh -F --continuous-integration HEAD
